import { Router } from "express";
import userRoutes from "./user/user.routes";
import adminRoutes from "./admin/admin.routes";
import ecommerceAuthRoutes from "../shared/auth/ecommerce.routes";
import fullRoutes from "./full/full.routes";

const router = Router();

router.get("/health", (_req, res) => {
  res.status(200).json({
    success: true,
    message: "Ecommerce module health",
    module: "ecommerce",
    availableApis: {
      profile: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/profile",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/profile",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/avatar",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/email",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/mobile",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/password",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/activity",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/preferences",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/preferences",
      ],
      address: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/address",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/address/:id",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/address",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/address/:id",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/address/:id",
        "PATCH /api/modules/ecommerce/user/:websiteId/:websiteSlug/address/default",
      ],
      home: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/banner",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/categories",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/featured-products",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/latest-products",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/best-selling",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/trending",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/home/offers",
      ],
      products: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/:slug",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/search",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/filter",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/recommended",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/related/:slug",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/latest",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/featured",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/trending",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/deals",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/products/new-arrivals",
      ],
      brands: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/brands",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/brands/:slug",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/brands/:slug/products",
      ],
      wishlist: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/wishlist",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/wishlist",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/wishlist/:productId",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/wishlist",
      ],
      cart: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart/:itemId",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart/:itemId",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart",
        "PATCH /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart/increase/:itemId",
        "PATCH /api/modules/ecommerce/user/:websiteId/:websiteSlug/cart/decrease/:itemId",
      ],
      coupon: [
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/coupon/apply",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/coupon/remove",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/coupon/available",
      ],
      checkout: [
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/checkout",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/checkout/shipping",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/checkout/payment",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/checkout/confirm",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/checkout/summary",
      ],
      orders: [
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id/invoice",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id/cancel",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id/return",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id/refund",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id/reorder",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/orders/:id/track",
      ],
      payment: [
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/payment/create-order",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/payment/verify",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/payment/history",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/payment/:id",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/payment/webhook",
      ],
      reviews: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/reviews/:productId",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/reviews",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/reviews/:id",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/reviews/:id",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/reviews/:id/helpful",
      ],
      notifications: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/notifications",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/notifications/read",
        "PUT /api/modules/ecommerce/user/:websiteId/:websiteSlug/notifications/read-all",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/notifications/:id",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/notifications",
      ],
      compare: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/compare",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/compare",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/compare/:productId",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/compare",
      ],
      recentlyViewed: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/recently-viewed",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/recently-viewed",
        "DELETE /api/modules/ecommerce/user/:websiteId/:websiteSlug/recently-viewed",
      ],
      support: [
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/support/ticket",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/support/tickets",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/support/ticket/:id",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/support/ticket/:id/reply",
      ],
      referral: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/referral",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/referral/invite",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/referral/history",
      ],
      giftCards: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/gift-cards",
        "POST /api/modules/ecommerce/user/:websiteId/:websiteSlug/gift-cards/redeem",
      ],
      loyalty: [
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/loyalty",
        "GET /api/modules/ecommerce/user/:websiteId/:websiteSlug/loyalty/history",
      ],
      admin: [
        "GET /api/modules/ecommerce/admin/users",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/users",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard/stats",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard/revenue",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard/orders",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard/customers",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard/products",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/dashboard/analytics",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/status",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/stock",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/featured",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/trending",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/import",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/export",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id/duplicate",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id/images",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id/images/:imageId",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id/images/order",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/products/:id/images/default",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/categories",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/categories",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/categories/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/categories/:id",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/categories/status",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/brands",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/brands",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/brands/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/brands/:id",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory/:productId",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory/add",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory/remove",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory/low-stock",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory/out-of-stock",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/inventory/history",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/:id",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/status",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/payment-status",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/shipping-status",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/assign-delivery",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/create",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/:id",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/:id/refund",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/:id/cancel",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/:id/return",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/orders/export",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/:id",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/:id",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/block",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/unblock",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/orders",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/customers/wallet",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/coupons",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/coupons",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/coupons/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/coupons/:id",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/coupons/status",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/reviews",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/reviews/:id",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/reviews/approve",
        "PATCH /api/modules/ecommerce/admin/:websiteId/:websiteSlug/reviews/reject",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/shipping",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/shipping",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/shipping/:id",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/shipping/zones",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/shipping/zones",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/taxes",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/taxes",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/taxes/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/taxes/:id",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/payments",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/payments/:id",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/payments/refund",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/payments/export",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/analytics/sales",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/analytics/orders",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/analytics/customers",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/analytics/products",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/analytics/revenue",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/analytics/traffic",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/notifications",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/notifications",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/notifications/:id",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/logo",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/favicon",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/seo",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/contact",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/social",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/currency",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/language",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/settings/timezone",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/delivery",
        "POST /api/modules/ecommerce/admin/:websiteId/:websiteSlug/delivery",
        "PUT /api/modules/ecommerce/admin/:websiteId/:websiteSlug/delivery/:id",
        "DELETE /api/modules/ecommerce/admin/:websiteId/:websiteSlug/delivery/:id",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/logs",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/logs/login",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/logs/activity",
        "GET /api/modules/ecommerce/admin/:websiteId/:websiteSlug/logs/errors",
      ],
      auth: {
        user: [
          "POST /api/modules/ecommerce/auth/user/:websiteId/:websiteSlug/signup",
          "POST /api/modules/ecommerce/auth/user/:websiteId/:websiteSlug/login",
        ],
        admin: [
          "POST /api/modules/ecommerce/auth/admin/:websiteId/:websiteSlug/login",
        ],
      },
      fullFlow: [
        "GET /api/modules/ecommerce/full/:websiteId/:websiteSlug",
        "GET /api/modules/ecommerce/full/demo",
      ],
    },
  });
});

router.use("/auth", ecommerceAuthRoutes);
router.use("/user", userRoutes);
router.use("/admin", adminRoutes);
router.use("/full", fullRoutes);

export default router;
