export {
  getCustomerProfile,
  updateCustomerProfile,
  updateCustomerAvatar,
  updateCustomerEmail,
  updateCustomerMobile,
  updateCustomerPassword,
  getCustomerActivity,
  getCustomerPreferences,
  updateCustomerPreferences,
  getProductsWithSlug,
  listAddresses,
  getAddressById,
  createAddress,
  updateAddress,
  deleteAddress,
  setDefaultAddress,
} from "./profile/profile.service";

export {
  getUserProducts,
  getUserProductById,
  getUserProductBySlug,
  getHomePageData,
  searchProducts,
  filterProducts,
  getRecommendedProducts,
  getRelatedProducts,
  getLatestProducts,
  getFeaturedProducts,
  getTrendingProducts,
  getDealsProducts,
  getNewArrivalsProducts,
  getBrands,
  getBrandBySlug,
  getBrandProducts,
} from "./catalog/catalog.service";

export {
  listWishlist,
  addWishlistItem,
  removeWishlistItem,
  clearWishlist,
  getCart,
  addCartItem,
  updateCartItem,
  deleteCartItem,
  clearCart,
  increaseCartItem,
  decreaseCartItem,
  applyCoupon,
  removeCoupon,
  getAvailableCoupons,
} from "./cart/cart.service";

export {
  createCheckout,
  setShipping,
  setPayment,
  confirmCheckout,
  getCheckoutSummary,
  createOrder,
  listOrders,
  getOrderById,
  getOrderInvoice,
  cancelOrder,
  returnOrder,
  refundOrder,
  reorderOrder,
  trackOrder,
  createPaymentOrder,
  verifyPayment,
  getPaymentHistory,
  getPaymentById,
  handlePaymentWebhook,
} from "./checkout/checkout.service";

export {
  listReviews,
  createReview,
  updateReview,
  deleteReview,
  markReviewHelpful,
  listNotifications,
  markNotificationsRead,
  markAllNotificationsRead,
  deleteNotification,
  clearNotifications,
  listCompare,
  addCompareItem,
  removeCompareItem,
  clearCompare,
  listRecentlyViewed,
  addRecentlyViewed,
  clearRecentlyViewed,
  createSupportTicket,
  listSupportTickets,
  getSupportTicket,
  replyToSupportTicket,
  getReferralInfo,
  inviteReferral,
  getReferralHistory,
  getGiftCards,
  redeemGiftCard,
  getLoyaltyInfo,
  getLoyaltyHistory,
} from "./support/support.service";

